--------------------------------------------------------------------------------
-- Copyright (c) 1995-2007 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 9.2i
--  \   \         Application : xaw2vhdl
--  /   /         Filename : clk100.vhd
-- /___/   /\     Timestamp : 09/12/2008 08:27:53
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-intstyle E:/p/wm-digital/cpu/wm3000/clk100.xaw -st clk100.vhd
--Design Name: clk100
--Device: xc3s400-4pq208
--
-- Module clk100
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST
-- Period Jitter (unit interval) for block DCM_INST = 0.07 UI
-- Period Jitter (Peak-to-Peak) for block DCM_INST = 0.74 ns

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity clkXtoY is
	 Generic (
	 -- compilerschalter
			clk_freq	: boolean			-- 0=25Mhz Quarz, 1=20Mhz Quarz
			);

   port ( 
			CLKIN_IN        : in    std_logic; 
         RST_IN          : in    std_logic; 
         clkout       : out   std_logic 
	);
end clkXtoY;

 --         CLKIN_IBUFG_OUT : out   std_logic; 
 --         CLK0_OUT        : out   std_logic; 
 --         LOCKED_OUT      : out   std_logic

architecture arch of clkXtoY is
   signal CLKFB_IN        : std_logic;
   signal CLKFX_OBUF      : std_logic;
   signal CLKIN_IBUFG     : std_logic;
   signal CLK0_BUF        : std_logic;
   signal GND_BIT         : std_logic;
begin
	clkout <= CLKFX_OBUF;
	
   GND_BIT <= '0';
 --  CLKIN_IBUFG_OUT <= CLKIN_IBUFG;
 --  CLK0_OUT <= CLKFB_IN;
--   CLKFX_OBUF_INST : BUFG		-- geändert alt IBUF
--      port map (I=>CLKFX_OBUF,
--                O=>CLKFX_OUT);
   
   CLKIN_IBUFG_INST : IBUFG
      port map (I=>CLKIN_IN,
                O=>CLKIN_IBUFG);
   
   CLK0_BUFG_INST : BUFG
      port map (I=>CLK0_BUF,
                O=>CLKFB_IN);
   
	u_20mhz: if (clk_freq)  generate
		DCM_INST : DCM_SP
		generic map( CLK_FEEDBACK => "1X",
					CLKDV_DIVIDE => 2.0,
					CLKFX_DIVIDE => 1,
					CLKFX_MULTIPLY => 5,-- alt 4
					CLKIN_DIVIDE_BY_2 => FALSE,
					CLKIN_PERIOD => 50.000, -- alt 40.000
					CLKOUT_PHASE_SHIFT => "NONE",
					DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
					DFS_FREQUENCY_MODE => "LOW",
					DLL_FREQUENCY_MODE => "LOW",
					DUTY_CYCLE_CORRECTION => TRUE,
					FACTORY_JF => x"8080",
					PHASE_SHIFT => 0,
					STARTUP_WAIT => FALSE)
			port map (CLKFB=>CLKFB_IN,
						 CLKIN=>CLKIN_IBUFG,
						 DSSEN=>GND_BIT,
						 PSCLK=>GND_BIT,
						 PSEN=>GND_BIT,
						 PSINCDEC=>GND_BIT,
						 RST=>RST_IN,
						 CLKDV=>open,
						 CLKFX=>CLKFX_OBUF,
						 CLKFX180=>open,
						 CLK0=>CLK0_BUF,
						 CLK2X=>open,
						 CLK2X180=>open,
						 CLK90=>open,
						 CLK180=>open,
						 CLK270=>open,
						 LOCKED=>open,
						 PSDONE=>open,
						 STATUS=>open);
		
		end generate;
	u_25mhz: if not(clk_freq)  generate
		DCM_INST : DCM_SP
		generic map( CLK_FEEDBACK => "1X",
					CLKDV_DIVIDE => 2.0,
					CLKFX_DIVIDE => 1,
					CLKFX_MULTIPLY => 4,-- alt 4
					CLKIN_DIVIDE_BY_2 => FALSE,
					CLKIN_PERIOD => 40.000, -- alt 40.000
					CLKOUT_PHASE_SHIFT => "NONE",
					DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
					DFS_FREQUENCY_MODE => "LOW",
					DLL_FREQUENCY_MODE => "LOW",
					DUTY_CYCLE_CORRECTION => TRUE,
					FACTORY_JF => x"8080",
					PHASE_SHIFT => 0,
					STARTUP_WAIT => FALSE)
			port map (CLKFB=>CLKFB_IN,
						 CLKIN=>CLKIN_IBUFG,
						 DSSEN=>GND_BIT,
						 PSCLK=>GND_BIT,
						 PSEN=>GND_BIT,
						 PSINCDEC=>GND_BIT,
						 RST=>RST_IN,
						 CLKDV=>open,
						 CLKFX=>CLKFX_OBUF,
						 CLKFX180=>open,
						 CLK0=>CLK0_BUF,
						 CLK2X=>open,
						 CLK2X180=>open,
						 CLK90=>open,
						 CLK180=>open,
						 CLK270=>open,
						 LOCKED=>open,
						 PSDONE=>open,
						 STATUS=>open);
		
		end generate;
		
end arch;


